### ISSUE TITLE
Fix placement on mobile

### ISSUE THREAD

**Issue by timii** [sentouki/Memory-Game#14]
For e.g. on Samsung Galaxy S5:
- memory canvas is shifted to the right
- footer is too far away from the bottom of the screen
➔ Possible Solution: Create media queries in css for mobile view
![image](https://user-images.githubusercontent.com/56680452/132127720-93e7d468-b056-4805-b96f-815d2203afce.png)

**Comment by sentouki** [comment]
suggestion for a possible design
<img src="https://user-images.githubusercontent.com/50547116/133176051-014e2a97-e394-4c73-bce1-68d206f74fea.png" width="400px"/>

**Comment by timii** [comment]
Thats a good idea. And the "Play again Button" is basically the "Restart" Button ?

**Comment by sentouki** [comment]
> And the "Play again Button" is basically the "Restart" Button ?

yes, exactly
