### ISSUE TITLE
error message when playing the flip sound

### ISSUE THREAD

**Issue by timii** [sentouki/Memory-Game#6]
Error message: 
![image](https://user-images.githubusercontent.com/56680452/131925058-5277ce11-81a1-4f0c-ba9b-a194300ba13b.png)

Potential threads about the error:
- https://github.com/processing/p5.js-sound/issues/506
- https://discourse.processing.org/t/error-when-playing-soundfile/23011
- https://gitmemory.com/issue/processing/p5.js-sound/506/756658958

**Comment by sentouki** [comment]
fixed in #28
